# Generated by Django 3.0.3 on 2020-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_account_id',
            field=models.TextField(default='no id', unique=True),
        ),
    ]
