# Generated by Django 3.0.3 on 2020-05-05 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20200505_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 17, 51, 20, 893698, tzinfo=utc)),
        ),
    ]
