#!/bin/bash
main() {
	cd /Users/jamullan/Documents/School/Carleton/SeniorFiles/AcadW20/COMPS/carleton-classifieds/classifieds/sample
	find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
	find . -path "*/migrations/*.pyc"  -delete
	cd ..
	rm db.sqlite3
}

main
