# Generated by Django 3.0.3 on 2020-05-08 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RideListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('datetime', models.DateTimeField()),
                ('passengers', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=8, max_digits=12)),
                ('endLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='main_app.Location')),
                ('startLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='main_app.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offerer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sold', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
