# Generated by Django 3.0.3 on 2020-05-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePosted', models.DateTimeField()),
                ('category', models.CharField(max_length=240)),
                ('prospective', models.BooleanField()),
                ('fulfilled', models.BooleanField()),
                ('title', models.TextField(default='N/A')),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('ALL', 'All')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('ALL', 'All')], max_length=7)),
                ('dummy_field', models.CharField(default='dummy', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='RidePosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfRide', models.DateTimeField()),
                ('startLocation', models.TextField()),
                ('endLocation', models.TextField()),
                ('numberOfPeople', models.IntegerField()),
                ('willingToPay', models.BooleanField()),
                ('payment', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Posting')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='savedBy',
            field=models.ManyToManyField(related_name='savedPostings', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='main_app.User'),
        ),
        migrations.CreateModel(
            name='ItemPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forSale', models.BooleanField()),
                ('forLoan', models.BooleanField()),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Posting')),
            ],
        ),
    ]
