# Generated by Django 3.0.2 on 2020-03-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='savedBy',
            field=models.ManyToManyField(to='main_app.User'),
        ),
        migrations.AddField(
            model_name='rideposting',
            name='payment',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='rideposting',
            name='willingToPay',
            field=models.TextField(default='no'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='poster', to='main_app.User'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
