# Generated by Django 3.0.3 on 2020-05-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200508_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='category',
            field=models.CharField(default='not specified', max_length=120),
        ),
    ]
