# Generated by Django 3.0.3 on 2020-05-11 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_itemlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridelisting',
            name='distance',
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='savedBy',
            field=models.ManyToManyField(related_name='savedItems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridelisting',
            name='savedBy',
            field=models.ManyToManyField(related_name='savedRides', to=settings.AUTH_USER_MODEL),
        ),
    ]
