# Generated by Django 3.0.3 on 2020-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200428_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dummy_field',
            field=models.CharField(default='dummy', max_length=240),
        ),
    ]
