# Generated by Django 3.0.3 on 2020-04-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20200420_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='title',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='itemposting',
            name='posting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Posting'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='savedBy',
            field=models.ManyToManyField(related_name='savedPostings', to='sample.User'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='sample.User'),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='posting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Posting'),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='willingToPay',
            field=models.BooleanField(),
        ),
    ]
